import Vue from 'vue';
import VmIcon from './VmIcon.vue';
import VmFormLabel from './VmFormLabel.vue';
import VmFormItem from './VmFormItem.vue';
import VmInput from './VmInput.vue';
import VmSelect from './VmSelect.vue';
import VmSlider from './VmSlider.vue';
import VmCollapse from './VmCollapse.vue';
import VmButtonGroup from './VmButtonGroup.vue';
import VmSlot from './VmSlot.vue';
import VmShape from './shape';
import VmWidget from './VmWidget.vue';
import VmColorPicker from './VmColorPicker.vue';
import VmDynamic from './VmDynamic.vue';

Vue.component('VmIcon', VmIcon);
Vue.component('VmFormLabel', VmFormLabel);
Vue.component('VmFormItem', VmFormItem);
Vue.component('VmInput', VmInput);
Vue.component('VmSelect', VmSelect);
Vue.component('VmSlider', VmSlider);
Vue.component('VmCollapse', VmCollapse);
Vue.component('VmButtonGroup', VmButtonGroup);
Vue.component('VmSlot', VmSlot);
Vue.component('VmShape', VmShape);
Vue.component('VmWidget', VmWidget);
Vue.component('VmColorPicker', VmColorPicker);
Vue.component('VmDynamic', VmDynamic);
